### ISSUE TITLE
MTS-ESP to Note Expression adds 1 client when DAW session is saved/closed

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/tuning-note-claps#10]
**MTS-ESP to Note Expression** is exhibiting the same adding a client during a saved session behavior

Add **MTS-ESP to Note Expression** to track 

Surge MTS-ESP Source lists 1 client. Save session in Bitwig 1 client remains. Re-open session and there are 2 clients. Save and/or close without saving, Client Count: 2, repeat, reopen/close session, Client Count: 3, close session and 3 clients remain.

**EDN-M To Note Expression** and **Fixed Offset Note Expression** do not exhibit this behavior

as an aside

`./mts-status --reset` only resets if **Can Register Master: 0**
would it possible to allow it to reset when it is also at **Can Register Master: 1** ?

Thanks

**Comment by baconpaul** [comment]
Oh thanks I probably don’t disconnect cleanly when destroyed. The gliss bug put this on pause but I will look!
