### ISSUE TITLE
EDM-N To Note Expression: Type-Ins Revert to 440 Hz for Tuning Center Frequency

### ISSUE THREAD

**Issue by ztnl** [surge-synthesizer/tuning-note-claps#5]
EDM-N To Note Expression: Type-Ins Revert to 440 Hz for Tuning Center Frequency | Windows 10

In testing the intonation with a middle C.60 reference, found that when trying to type-in 261.626 Hz, upon pressing enter, it reverts to 440 Hz A.

**Comment by baconpaul** [comment]
Fixed in the upcoming 0.9.0 release.
